// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTemplate.Infra.Data.Contexto;

namespace ProjectTemplate.Infra.Data.Migrations
{
    [DbContext(typeof(BaseContexto))]
    [Migration("20201115014403_202011142243_MudancaToStringSomeModels")]
    partial class _202011142243_MudancaToStringSomeModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectTemplate.Application.DTOs.Edificacoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COD_EDIFICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("COMPLEMENTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FUNCIONARIOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDENT_GLOBAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCALIDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOME_LOGRADOURO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NUMERO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_RESIDENTES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONTO_ENCONTRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TIPO_LOGRADOURO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTM_X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTM_Y")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("COD_EDIFICACAO")
                        .IsUnique();

                    b.ToTable("Edificacoes");
                });

            modelBuilder.Entity("ProjectTemplate.Application.DTOs.EdificacoesMoradores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COD_EDIFICACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IDADE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDENT_GLOBAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LONG_")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONTO_ENCONTRO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELACAO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELACAO_FAMILIAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEXO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELEFONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTM_X")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTM_Y")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("COD_EDIFICACAO")
                        .IsUnique();

                    b.ToTable("EdificacoesMoradores");
                });

            modelBuilder.Entity("ProjectTemplate.Application.DTOs.PontosEncontro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Refer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PontosEncontro");
                });

            modelBuilder.Entity("ProjectTemplate.Application.DTOs.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
